### ISSUE TITLE
Déploiement GitHub Pages

### ISSUE THREAD

**Issue by chikamichi** [O-clock-Dev/PSR-en-francais#2]
Créer un petit script qui génère automatiquement un site statique, un MkDocs, quelque chose… pour une consultation plus cool, avec une recherche idéalement (d’où MkDocs).

À héberger sur https://psr.oclock.io ou https://dev.oclock.io/psr/ pour se faire un peu de pub au passage ? (et intégrer un lien/logo vers https://oclock.io/ dans l’output générée)

**Comment by oclock-bot-leon** [comment]
Ça fait plus d'un an qu'on n'a pas avancé là-dessus. Cette issue est-elle encore d'actualité ? En l'absence d'une réponse, je me permettrai de fermer l'issue dans un mois.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.
